name: tfjs_browser

dependencies:
  - python=3.10
  - pytorch::pytorch
  - pip
  - transformers[onnx]
  - onnxruntime
  - pip:
    - ipywidgets
    - ipykernel
    - datasets
    - accelerate >= 0.12.0
    - datasets >= 1.8.0
    - sentencepiece != 0.1.92
    - scipy
    - scikit-learn
    - protobuf
    - torch >= 1.3
    - evaluate
    - onnxruntime
